### ISSUE TITLE
BUG-When downloading a byte stream we don't get the expected file name

### ISSUE THREAD

**Issue by gbritoda** [Avaiga/taipy-gui#966] opened 2023-10-10 11:10 UTC
**Description**
According to the [manual on file_download](https://docs.taipy.io/en/release-2.3/manuals/gui/viselements/file_download/), if we put `name=something`, we get that as a suggested download name when we download our file.
However, I've been getting `TaiPyContent.bin` whenever I try to download a byte stream  from python (and not an actual physical file).

See example code below

**How to reproduce**
```python
from taipy.gui import Gui, State

DOWNLOAD_CONTENT = b"Content"

page = """
<|{DOWNLOAD_CONTENT}|file_download|name=my_downloadable_file.txt|>
"""

GUI_OBJ = Gui(page=page)
GUI_OBJ.run(
        host="0.0.0.0",
        port=1234,
        dark_mode=False,
        debug=True,
        use_reloader=True,
)
```

**Expected behavior**
When clicking downloading, should get a file named `my_downloadable_file.txt`, but we get `TaipyContent.bin` instead.

**Screenshots**
![image](https://github.com/Avaiga/taipy-gui/assets/33906448/86b1cd45-dc94-4d2a-8a24-98f4a3688291)

**Runtime environment**

 - OS: WSL Ubuntu 22.04.2 LTS
 - Browser: Firefox 118.0.1 (64 bit)
- TaiPy 2.4.0

**Comment by FredLL-Avaiga** [comment] 2023-10-10 11:43
duplicate of Avaiga/taipy#433

**Closed as completed** 2023-10-10 11:43 UTC
Labels: 💥Malfunction
