### ISSUE TITLE
Editing table cells with enum values 

### ISSUE THREAD

**Issue by bobbyshermi** [Avaiga/taipy-gui#750] opened 2023-05-18 07:58 UTC
I am building a configuration document graphically using Taipy. The purpose is to work collaboratively on the same config.
I want to display an editable table with 3 columns: a configuration parameter, its value and its type. The type column can only be populated with enums (predefined fixed values).

For editing a cell in the type column, I would like to be able to select the value among the predefined possible values.

**Comment by bobbyshermi** [comment] 2023-05-25 10:40
Sorry I just saw issue Avaiga/taipy#556 I believe it is related.

**Comment by FabienLelaquais** [comment] 2023-05-26 06:36
Indeed these issues seem identical.
The R&D team is currently looking at providing that feature.

The whole point of having Taipy GUI take care of that requirement is to keep compatibility with data structures that do not provide such a feature, such as the Pandas DataFrames.
We plan to provide a new property to the table control where you would be able to indicate the possible values for a given column. That would look like `enum[<column_name>]=<list_of_valid_values>`.
Then users would not be able to edit a cell and provide a value that is not listed in the given set.

However, we are still struggling to find an elegant manner to allow for exceptions: you would provide a list of valid values just like described above, but the table should be able to let any value be set anyways.  That feature seems mandatory and we are not quite ready yet to provide it.

I will link this issue with the one you have found, to better focus on the task at hand.

**Comment by FabienLelaquais** [comment] 2023-05-26 06:38
Duplicate of Avaiga/taipy#556.

**Closed as completed by FabienLelaquais** 2023-05-26 06:38 UTC
Labels: 📈 Improvement, GUI: Front-End, 🟧 Priority: High
