### ISSUE TITLE
BUG- persistent property not working for pane

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#663] opened 2023-03-14 14:46 UTC
**Description**
The [documentation for pane](https://docs.taipy.io/en/latest/manuals/gui/viselements/pane/) states that persistent set to True will put the pane next to the page and will not cover it. However, persistent set to True will cover the page.

> persistent | bool | False | If True, the pane appears next to the page. If False, the pane covers the page where it appeared.

**How to reproduce**
```python
from taipy.gui import Gui, notify

md = """
<|{True}|pane|persistent|on_change={lambda s: notify(s, 'e', 'Persistent')}|
Hello
|>


# Test Pane

oiufwqhwoijoco ijo il buhigb ljlih uhylu hujbjhb kuhyv
"""

Gui(md).run(port=5500)
```

**Expected behavior**
Description of what would be the expected outcome.

**Screenshots**
![image](https://user-images.githubusercontent.com/98709993/225037133-56d52c07-61f5-48b2-a08c-6dedeb9539dd.png)

**Runtime environment**
Taipy GUI: 2.1.0

**Comment by FredLL-Avaiga** [comment] 2023-03-21 09:03
The problem is that the Pane and the rest of the content need to be embedded in a div with style display: flex.
Which is external to the component :-(

It displays correctly with this setup:
CSS file
```
.flexdiv{
    display: flex;
}

```

app

```
from taipy.gui import Gui, notify

md = """
<|flexdiv|
<|{True}|pane|persistent|on_change={lambda s: notify(s, 'e', 'Persistent')}|
Hello
|>

<|
# Test Pane

oiufwqhwoijoco ijo il buhigb ljlih uhylu hujbjhb kuhyv
|>
|>
"""

Gui(md).run()
```

**Comment by FlorianJacta** [comment] 2023-03-21 09:43
Thanks, I see! Is there something we can do about it? Maybe with the stylekit? Or can we document it in the docs to know how to use the persistent property?

**Comment by FredLL-Avaiga** [comment] 2023-03-21 09:59
I guess it will be mainly a documentation issue.
What do you think @FabienLelaquais ?
and we might want to add the CSS class flexdiv to stylekit ?

**Comment by FabienLelaquais** [comment] 2023-03-21 13:33
I think that I hate components that don't behave properly on their own.
Now obviously, this is a special case, since it shares its space with siblings.
I would therefore agree that a line of doc would help.

Adding a class to the StyleKit for this specific case makes little sense to me at this point.

**Comment by FabienLelaquais** [comment] 2023-04-13 13:36
This is resolved with better documentation.
See &lt;taipy-doc-site&gt;/manuals/gui/viselements/pane/#showing-the-pane-beside-the-page-content.

**Closed as completed** 2023-04-21 09:21 UTC
Labels: 💥Malfunction, 🟨 Priority: Medium
